spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_test?characterEncoding=UTF-8&useUnicode=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 1036858975A